: MUL2  
  DUP 2 * SWAP DROP ;

: DIV2  
  DUP 2 / SWAP DROP ;

: P_HEX
  CR DUP hex. ;

: SCAN_UP
  BEGIN DUP 128 < WHILE MUL2 P_HEX REPEAT ;

: SCAN_DOWN
  BEGIN DUP 1 > WHILE DIV2 P_HEX REPEAT ;

: KITT
  1 BEGIN 1 1 = WHILE SCAN_UP SCAN_DOWN REPEAT ;
